### ISSUE TITLE
Addgif broken for non-admin users

### ISSUE THREAD

**Issue by Sar4h-3** [BlackDemonFire/lukas#394]
While testing for #390, I noticed that the function for non-admins to add a gif is broken. 
While you, as an admin can accept the request, nothing happens after.

**Comment by KommentatorForAll** [comment]
The cause seems to be missing permissions for direct message reactions.
Though adding it causes the bot to lose connection to the db for some reason

**Comment by KommentatorForAll** [comment]
merged in #397
